language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install tox-travis

env:
  - EXAMPLE=1

# command to run tests
script: tox -r -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)